# Notebook 6 – Data Inspection

## Topics Covered

- `head()`
- `tail()`
- `sample()`
- `info()`
- `describe()`
- `shape`
- `columns`
- `dtypes`
- `memory_usage()`
- `nunique()`
- `value_counts()`

# 1. Introduction to Data Inspection

Data inspection means checking and understanding a dataset before performing analysis.

It helps us understand:

- What the data looks like
- Number of rows and columns
- Column names
- Data types
- Missing values
- Statistical information
- Unique values
- Memory usage
- Distribution of categorical values

Pandas provides several functions and attributes for inspecting DataFrames.

# 2. Import Pandas

First, import the Pandas library.

In [1]:
import pandas as pd

# 3. Create a Sample DataFrame

We will use the following DataFrame throughout this notebook.

In [2]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma", "Frank", "Grace", "Henry"],
    "Age": [22, 25, 21, 28, 24, 30, 26, 23],
    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "IT", "Finance", "IT"
    ],
    "Salary": [50000, 45000, 55000, 60000, 48000, 70000, 65000, 52000],
    "Experience": [1, 2, 1, 5, 2, 7, 4, 2]
}

df = pd.DataFrame(data)

print(df)

      Name  Age Department  Salary  Experience
0    Alice   22         IT   50000           1
1      Bob   25         HR   45000           2
2  Charlie   21         IT   55000           1
3    David   28    Finance   60000           5
4     Emma   24         HR   48000           2
5    Frank   30         IT   70000           7
6    Grace   26    Finance   65000           4
7    Henry   23         IT   52000           2

# 4. head()

The `head()` method displays the first few rows of a DataFrame.

By default, it displays the first 5 rows.

### Syntax

`df.head()`

### Why use it?

It is useful for quickly checking:

- Column names
- First few records
- Data format
- Whether the data was loaded correctly

In [3]:
df.head()

      Name  Age Department  Salary  Experience
0    Alice   22         IT   50000           1
1      Bob   25         HR   45000           2
2  Charlie   21         IT   55000           1
3    David   28    Finance   60000           5
4     Emma   24         HR   48000           2

## Display a Specific Number of Rows

We can provide a number inside `head()`.

For example:

`df.head(3)`

displays the first 3 rows.

In [4]:
df.head(3)

      Name  Age Department  Salary  Experience
0    Alice   22         IT   50000           1
1      Bob   25         HR   45000           2
2  Charlie   21         IT   55000           1

# 5. tail()

The `tail()` method displays the last few rows of a DataFrame.

By default, it displays the last 5 rows.

### Syntax

`df.tail()`

### Why use it?

It is useful for checking:

- The end of the dataset
- Whether data was loaded completely
- The last few records

In [5]:
df.tail()

    Name  Age Department  Salary  Experience
3  David   28    Finance   60000           5
4   Emma   24         HR   48000           2
5  Frank   30         IT   70000           7
6  Grace   26    Finance   65000           4
7  Henry   23         IT   52000           2

## Display a Specific Number of Last Rows

We can specify the number of rows.

For example:

`df.tail(3)`

displays the last 3 rows.

In [6]:
df.tail(3)

    Name  Age Department  Salary  Experience
5  Frank   30         IT   70000           7
6  Grace   26    Finance   65000           4
7  Henry   23         IT   52000           2

# 6. sample()

The `sample()` method randomly selects rows from a DataFrame.

### Syntax

`df.sample()`

By default, it returns one random row.

### Why use it?

It is useful when:

- The dataset is very large
- We want to randomly inspect records
- We want to check whether the data contains unexpected values

In [7]:
df.sample()

    Name  Age Department  Salary  Experience
0  Alice   22         IT   50000           1

## Selecting Multiple Random Rows

We can specify the number of rows to randomly select.

For example:

`df.sample(3)`

selects 3 random rows.

In [8]:
df.sample(3)

    Name  Age Department  Salary  Experience
7  Henry   23         IT   52000           2
1    Bob   25         HR   45000           2
5  Frank   30         IT   70000           7

## Random Sample with a Fixed Seed

We can use `random_state` to get the same random sample every time.

This is useful when we want reproducible results.

In [9]:
df.sample(3, random_state=42)

    Name  Age Department  Salary  Experience
1    Bob   25         HR   45000           2
5  Frank   30         IT   70000           7
0  Alice   22         IT   50000           1

# 7. info()

The `info()` method provides a summary of the DataFrame.

It displays:

- Number of rows
- Number of columns
- Column names
- Number of non-null values
- Data types
- Memory usage

### Syntax

`df.info()`

### Why use it?

It is one of the most useful methods for quickly understanding a dataset.

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      str
 1   Age         8 non-null      int64
 2   Department  8 non-null      str
 3   Salary      8 non-null      int64
 4   Experience  8 non-null      int64
dtypes: int64(3), str(2)
memory usage: 517.0 bytes

## Understanding info()

For example:

`RangeIndex: 8 entries`

means the DataFrame contains 8 rows.

`8 non-null`

means all 8 rows contain a value for that column.

`int64`

means the column contains integer values.

`object`

usually indicates text/string data in many Pandas DataFrames.

`memory usage`

shows approximately how much memory the DataFrame uses.

# 8. describe()

The `describe()` method provides statistical summary information for numerical columns.

It commonly displays:

- count
- mean
- standard deviation
- minimum
- 25th percentile
- 50th percentile
- 75th percentile
- maximum

### Syntax

`df.describe()`

In [11]:
df.describe()

             Age       Salary  Experience
count   8.000000      8.00000     8.00000
mean   24.875000  55625.00000     3.00000
std     3.044316   8700.36945     2.13809
min    21.000000  45000.00000     1.00000
25%    22.750000  49500.00000     1.75000
50%    24.500000  53500.00000     2.00000
75%    26.500000  61250.00000     4.25000
max    30.000000  70000.00000     7.00000

## Understanding describe()

### count

Number of non-missing values.

### mean

Average value.

### std

Standard deviation, which measures the spread of the values.

### min

Smallest value.

### 25%

First quartile (Q1).

### 50%

Median (Q2).

### 75%

Third quartile (Q3).

### max

Largest value.

## Describe a Specific Column

We can also calculate descriptive statistics for a single column.

In [13]:
df["Salary"].describe()

count        8.00000
mean     55625.00000
std       8700.36945
min      45000.00000
25%      49500.00000
50%      53500.00000
75%      61250.00000
max      70000.00000
Name: Salary, dtype: float64

## Include Categorical Columns

By default, `describe()` focuses on numerical columns.

We can use:

`include="object"`

to describe object/string columns.

In [14]:
df.describe(include="object")

C:\Users\akile\AppData\Local\Temp\ipykernel_35064\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

         Name Department
count       8          8
unique      8          3
top     Alice         IT
freq        1          4

## Describe All Columns

We can use:

`include="all"`

to generate descriptive information for both numerical and non-numerical columns.

In [15]:
df.describe(include="all")

         Name        Age Department       Salary  Experience
count       8   8.000000          8      8.00000     8.00000
unique      8        NaN          3          NaN         NaN
top     Alice        NaN         IT          NaN         NaN
freq        1        NaN          4          NaN         NaN
mean      NaN  24.875000        NaN  55625.00000     3.00000
std       NaN   3.044316        NaN   8700.36945     2.13809
min       NaN  21.000000        NaN  45000.00000     1.00000
25%       NaN  22.750000        NaN  49500.00000     1.75000
50%       NaN  24.500000        NaN  53500.00000     2.00000
75%       NaN  26.500000        NaN  61250.00000     4.25000
max       NaN  30.000000        NaN  70000.00000     7.00000

# 9. shape

The `shape` attribute returns the dimensions of a DataFrame.

It returns:

`(number_of_rows, number_of_columns)`

### Syntax

`df.shape`

### Example

If the result is:

`(8, 5)`

it means:

- 8 rows
- 5 columns

### Important

`shape` is an attribute, so we do not use parentheses.

In [16]:
df.shape

(8, 5)

## Number of Rows and Columns

We can unpack the shape into two variables.

In [17]:
rows, columns = df.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 8
Number of columns: 5

# 10. columns

The `columns` attribute returns the names of all columns in a DataFrame.

### Syntax

`df.columns`

### Why use it?

It is useful for:

- Checking column names
- Selecting columns
- Renaming columns
- Understanding dataset structure

In [18]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='str')

## Convert Column Names to a List

In [19]:
list(df.columns)

['Name', 'Age', 'Department', 'Salary', 'Experience']

# 11. dtypes

The `dtypes` attribute displays the data type of each column.

### Syntax

`df.dtypes`

Common data types include:

- `int64` → Integer
- `float64` → Decimal number
- `object` → Usually text/string
- `bool` → True/False
- `datetime64` → Date and time

### Why use it?

Data types are important because different operations work differently depending on the type of data.

In [20]:
df.dtypes

Name            str
Age           int64
Department      str
Salary        int64
Experience    int64
dtype: object

## Check the Data Type of One Column

In [21]:
print("Age:", df["Age"].dtype)
print("Salary:", df["Salary"].dtype)
print("Name:", df["Name"].dtype)

Age: int64
Salary: int64
Name: str

# 12. memory_usage()

The `memory_usage()` method shows how much memory is being used by each column.

### Syntax

`df.memory_usage()`

This is useful when working with large datasets.

### Why is memory usage important?

Large datasets can consume a lot of RAM.

Understanding memory usage helps us:

- Optimize datasets
- Reduce memory consumption
- Improve performance
- Work with larger datasets

In [22]:
df.memory_usage()

Index         132
Name          103
Age            64
Department     90
Salary         64
Experience     64
dtype: int64

## Include Object Memory Usage

For object/string columns, Pandas may not include the full size of the referenced objects by default.

We can use:

`deep=True`

to get a more detailed memory estimate.

In [23]:
df.memory_usage(deep=True)

Index         132
Name          103
Age            64
Department     90
Salary         64
Experience     64
dtype: int64

## Total Memory Usage

We can calculate the total memory used by the DataFrame.

In [24]:
total_memory = df.memory_usage(deep=True).sum()

print("Total memory usage:", total_memory, "bytes")

Total memory usage: 517 bytes

# 13. nunique()

The `nunique()` method returns the number of unique values in each column.

### Syntax

`df.nunique()`

### Why use it?

It is useful for understanding:

- Number of unique categories
- Number of different values
- Categorical columns
- Potential duplicate values

In [27]:
df.nunique()

Name          8
Age           8
Department    3
Salary        8
Experience    5
dtype: int64

## Unique Values in a Specific Column

In [28]:
print("Unique departments:", df["Department"].nunique())
print("Unique ages:", df["Age"].nunique())

Unique departments: 3
Unique ages: 8

## `nunique()` with `dropna`

By default, missing values are not counted as unique values.

We can use:

`dropna=False`

to include missing values in the count.

In [29]:
df.nunique(dropna=False)

Name          8
Age           8
Department    3
Salary        8
Experience    5
dtype: int64

# 14. value_counts()

The `value_counts()` method counts how frequently each unique value appears in a Series.

### Syntax

`df["column"].value_counts()`

### Why use it?

It is especially useful for categorical data.

For example, we can find:

- Number of employees in each department
- Number of students in each grade
- Number of customers in each city
- Number of products in each category

In [30]:
df["Department"].value_counts()

Department
IT         4
HR         2
Finance    2
Name: count, dtype: int64

## Example

If the Department column contains:

IT
IT
HR
Finance
IT

Then:

`value_counts()`

will show the number of occurrences of each department.

## value_counts() for Another Column

In [31]:
df["Age"].value_counts()

Age
22    1
25    1
21    1
28    1
24    1
30    1
26    1
23    1
Name: count, dtype: int64

## Sort by Index

By default, `value_counts()` sorts by frequency.

We can sort by the values themselves using:

`sort_index()`

In [32]:
df["Department"].value_counts().sort_index()

Department
Finance    2
HR         2
IT         4
Name: count, dtype: int64

## Convert Counts to Percentages

We can use:

`normalize=True`

to get the proportion of each value instead of the count.

In [33]:
df["Department"].value_counts(normalize=True)

Department
IT         0.50
HR         0.25
Finance    0.25
Name: proportion, dtype: float64

## Convert Counts to Percentages

We can multiply the normalized values by 100.

In [34]:
department_percentage = (
    df["Department"]
    .value_counts(normalize=True) * 100
)

print(department_percentage)

Department
IT         50.0
HR         25.0
Finance    25.0
Name: proportion, dtype: float64

# 15. Data Inspection Methods Comparison

| Method / Attribute | Purpose |
|---|---|
| `head()` | View first rows |
| `tail()` | View last rows |
| `sample()` | View random rows |
| `info()` | Get DataFrame structure and data types |
| `describe()` | Get statistical summary |
| `shape` | Get rows and columns |
| `columns` | Get column names |
| `dtypes` | Get column data types |
| `memory_usage()` | Check memory usage |
| `nunique()` | Count unique values |
| `value_counts()` | Count frequency of values |