# Notebook 7 – Selecting & Filtering Data

This notebook covers different techniques used to select, filter, and sort data in Pandas.

## Topics Covered

- `loc`
- `iloc`
- Boolean Indexing
- Filtering Rows
- `query()`
- `isin()`
- `between()`
- Sorting Data

## 1. Import Pandas

Pandas is a Python library used for data manipulation and analysis.

In [2]:
import pandas as pd

## Creating a Sample DataFrame

We will use the following DataFrame to understand data selection and filtering.

In [3]:
data = {
    "Name": ["Arun", "Bala", "Charan", "Divya", "Elango", "Fathima"],
    "Age": [22, 25, 28, 21, 30, 26],
    "City": ["Chennai", "Bangalore", "Chennai", "Hyderabad", "Bangalore", "Chennai"],
    "Salary": [30000, 45000, 50000, 28000, 60000, 42000],
    "Department": ["IT", "HR", "IT", "Finance", "IT", "HR"]
}

df = pd.DataFrame(data)

df

      Name  Age       City  Salary Department
0     Arun   22    Chennai   30000         IT
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
3    Divya   21  Hyderabad   28000    Finance
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

## 2. loc

`loc` is used to select rows and columns using **labels**.

### Syntax

```python
df.loc[row_label, column_label]

```
It can be used to:

- Select specific rows
- Select specific columns
- Select a range of rows
- Filter rows using conditions

In [5]:
# Select the first row

df.loc[0]

Name             Arun
Age                22
City          Chennai
Salary          30000
Department         IT
Name: 0, dtype: object

In [4]:
# Select rows from index 0 to 2

df.loc[0:2]

     Name  Age       City  Salary Department
0    Arun   22    Chennai   30000         IT
1    Bala   25  Bangalore   45000         HR
2  Charan   28    Chennai   50000         IT

In [6]:
# Select a specific column

df.loc[:, "Name"]

0       Arun
1       Bala
2     Charan
3      Divya
4     Elango
5    Fathima
Name: Name, dtype: str

In [7]:
# Select multiple columns

df.loc[:, ["Name", "Salary"]]

      Name  Salary
0     Arun   30000
1     Bala   45000
2   Charan   50000
3    Divya   28000
4   Elango   60000
5  Fathima   42000

In [8]:
# Select specific rows and columns

df.loc[0:2, ["Name", "Salary"]]

     Name  Salary
0    Arun   30000
1    Bala   45000
2  Charan   50000

In [9]:
# Select rows where salary is greater than 40000

df.loc[df["Salary"] > 40000]

      Name  Age       City  Salary Department
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

## 3. iloc

`iloc` is used to select rows and columns using **integer positions**.

### Syntax

```python
df.iloc[row_position, column_position]

In [10]:

# Select the first row

df.iloc[0]

Name             Arun
Age                22
City          Chennai
Salary          30000
Department         IT
Name: 0, dtype: object

In [11]:
# Select the first three rows

df.iloc[0:3]

     Name  Age       City  Salary Department
0    Arun   22    Chennai   30000         IT
1    Bala   25  Bangalore   45000         HR
2  Charan   28    Chennai   50000         IT

In [12]:
# Select the first column

df.iloc[:, 0]

0       Arun
1       Bala
2     Charan
3      Divya
4     Elango
5    Fathima
Name: Name, dtype: str

In [13]:
# Select the first two columns

df.iloc[:, 0:2]

      Name  Age
0     Arun   22
1     Bala   25
2   Charan   28
3    Divya   21
4   Elango   30
5  Fathima   26

In [14]:
# Select rows 0 to 2 and columns 0 to 2

df.iloc[0:3, 0:3]

     Name  Age       City
0    Arun   22    Chennai
1    Bala   25  Bangalore
2  Charan   28    Chennai

In [15]:
# Select specific rows and columns

df.iloc[[0, 2, 4], [0, 3]]

     Name  Salary
0    Arun   30000
2  Charan   50000
4  Elango   60000

## 4. Boolean Indexing

Boolean indexing is used to filter data based on a condition.

The condition returns `True` or `False` for each row.

### Example

```python
df["Age"] > 25

In [16]:
# Check which employees are older than 25

df["Age"] > 25

0    False
1    False
2     True
3    False
4     True
5     True
Name: Age, dtype: bool

In [17]:
# Select employees older than 25

df[df["Age"] > 25]

      Name  Age       City  Salary Department
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [18]:
# Multiple conditions using AND (&)

df[(df["Age"] > 25) & (df["Salary"] > 40000)]

      Name  Age       City  Salary Department
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [19]:
# Multiple conditions using OR (|)

df[(df["City"] == "Chennai") | (df["City"] == "Bangalore")]

      Name  Age       City  Salary Department
0     Arun   22    Chennai   30000         IT
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

## 5. Filtering Rows

Filtering is used to select only the rows that satisfy a particular condition.

Common filtering operators:

- `>`
- `<`
- `>=`
- `<=`
- `==`
- `!=`
- `&` – AND
- `|` – OR

In [20]:
# Filter employees from Chennai

df[df["City"] == "Chennai"]

      Name  Age     City  Salary Department
0     Arun   22  Chennai   30000         IT
2   Charan   28  Chennai   50000         IT
5  Fathima   26  Chennai   42000         HR

In [21]:
# Filter employees from IT department

df[df["Department"] == "IT"]

     Name  Age       City  Salary Department
0    Arun   22    Chennai   30000         IT
2  Charan   28    Chennai   50000         IT
4  Elango   30  Bangalore   60000         IT

In [22]:
# Filter employees with salary less than or equal to 40000

df[df["Salary"] <= 40000]

    Name  Age       City  Salary Department
0   Arun   22    Chennai   30000         IT
3  Divya   21  Hyderabad   28000    Finance

In [23]:
# Filter employees between age 25 and 30

df[(df["Age"] >= 25) & (df["Age"] <= 30)]

      Name  Age       City  Salary Department
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

## 6. query()

`query()` is used to filter rows using a string expression.

It provides a cleaner way to write some filtering conditions.

### Syntax

```python
df.query("condition")

In [24]:
# Employees older than 25

df.query("Age > 25")

      Name  Age       City  Salary Department
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [25]:
# Employees from Chennai

df.query("City == 'Chennai'")

      Name  Age     City  Salary Department
0     Arun   22  Chennai   30000         IT
2   Charan   28  Chennai   50000         IT
5  Fathima   26  Chennai   42000         HR

In [26]:
# Multiple conditions

df.query("Age > 25 and Salary > 40000")

      Name  Age       City  Salary Department
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

## 7. isin()

`isin()` is used to check whether values belong to a specified list of values.

It is useful when we want to filter rows based on multiple possible values.

### Syntax

```python
df["column"].isin([value1, value2, value3])

In [27]:
# Employees from Chennai or Bangalore

df[df["City"].isin(["Chennai", "Bangalore"])]

      Name  Age       City  Salary Department
0     Arun   22    Chennai   30000         IT
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [28]:
# Employees from IT or HR departments

df[df["Department"].isin(["IT", "HR"])]

      Name  Age       City  Salary Department
0     Arun   22    Chennai   30000         IT
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [29]:
# Check whether each city is Chennai or Hyderabad

df["City"].isin(["Chennai", "Hyderabad"])

0     True
1    False
2     True
3     True
4    False
5     True
Name: City, dtype: bool

## 8. between()

`between()` is used to check whether values fall within a specified range.

### Syntax

```python
df["column"].between(lower, upper)

In [31]:
# Employees whose age is between 25 and 30

df[df["Age"].between(25, 30)]

      Name  Age       City  Salary Department
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [32]:
# Employees whose salary is between 30000 and 50000

df[df["Salary"].between(30000, 50000)]

      Name  Age       City  Salary Department
0     Arun   22    Chennai   30000         IT
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
5  Fathima   26    Chennai   42000         HR

In [33]:
# Age between 25 and 30, excluding the boundaries

df[df["Age"].between(25, 30, inclusive="neither")]

      Name  Age     City  Salary Department
2   Charan   28  Chennai   50000         IT
5  Fathima   26  Chennai   42000         HR

## 9. Sorting Data

Sorting is used to arrange DataFrame rows in ascending or descending order.

The main method used is:

```python
sort_values()

In [36]:
df.sort_values("Name")

      Name  Age       City  Salary Department
0     Arun   22    Chennai   30000         IT
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
3    Divya   21  Hyderabad   28000    Finance
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [37]:
# Sort by salary in ascending order

df.sort_values("Salary", ascending=True)

      Name  Age       City  Salary Department
3    Divya   21  Hyderabad   28000    Finance
0     Arun   22    Chennai   30000         IT
5  Fathima   26    Chennai   42000         HR
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT

In [38]:
# Sort by salary in descending order

df.sort_values("Salary", ascending=False)

      Name  Age       City  Salary Department
4   Elango   30  Bangalore   60000         IT
2   Charan   28    Chennai   50000         IT
1     Bala   25  Bangalore   45000         HR
5  Fathima   26    Chennai   42000         HR
0     Arun   22    Chennai   30000         IT
3    Divya   21  Hyderabad   28000    Finance

In [39]:
# Sort by multiple columns

df.sort_values(["Department", "Salary"])

      Name  Age       City  Salary Department
3    Divya   21  Hyderabad   28000    Finance
5  Fathima   26    Chennai   42000         HR
1     Bala   25  Bangalore   45000         HR
0     Arun   22    Chennai   30000         IT
2   Charan   28    Chennai   50000         IT
4   Elango   30  Bangalore   60000         IT

In [41]:
# Sort department ascending and salary descending

df.sort_values(
    ["Department", "Salary"],
    ascending=[True, False]
)

      Name  Age       City  Salary Department
3    Divya   21  Hyderabad   28000    Finance
1     Bala   25  Bangalore   45000         HR
5  Fathima   26    Chennai   42000         HR
4   Elango   30  Bangalore   60000         IT
2   Charan   28    Chennai   50000         IT
0     Arun   22    Chennai   30000         IT

## 10. Sorting by Index

`sort_index()` is used to sort the DataFrame based on its index.

In [42]:
# Sort by index

df.sort_index()

      Name  Age       City  Salary Department
0     Arun   22    Chennai   30000         IT
1     Bala   25  Bangalore   45000         HR
2   Charan   28    Chennai   50000         IT
3    Divya   21  Hyderabad   28000    Finance
4   Elango   30  Bangalore   60000         IT
5  Fathima   26    Chennai   42000         HR

In [43]:
# Sort index in descending order

df.sort_index(ascending=False)

      Name  Age       City  Salary Department
5  Fathima   26    Chennai   42000         HR
4   Elango   30  Bangalore   60000         IT
3    Divya   21  Hyderabad   28000    Finance
2   Charan   28    Chennai   50000         IT
1     Bala   25  Bangalore   45000         HR
0     Arun   22    Chennai   30000         IT

## 12. Difference Between loc and iloc

| Feature | loc | iloc |
|---|---|---|
| Selection type | Label-based | Position-based |
| Uses | Row/column labels | Integer positions |
| Example | `df.loc[0]` | `df.iloc[0]` |
| Column selection | `df.loc[:, "Name"]` | `df.iloc[:, 0]` |
| Filtering | Supports conditions | Mainly position-based selection |

### Simple Rule

- Use `loc` when you know the **label/name**.
- Use `iloc` when you know the **position/index number**.

# Summary

In this notebook, we learned:

- `loc` – Select data using labels.
- `iloc` – Select data using integer positions.
- Boolean Indexing – Filter data using conditions.
- Filtering Rows – Select rows that satisfy conditions.
- `query()` – Filter rows using expressions.
- `isin()` – Filter rows based on multiple values.
- `between()` – Filter values within a range.
- `sort_values()` – Sort data by one or more columns.
- `sort_index()` – Sort data based on the index.

These techniques are commonly used in Pandas for selecting, filtering, and organizing data during data analysis.